name: Create Precompiled archive

on: push

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: Installing Node
      uses: actions/setup-node@v1
      if: startsWith(github.ref, 'refs/tags/')
      with:
        node-version: 10.x
    - name: Installing dependancies
      if: startsWith(github.ref, 'refs/tags/')
      run: |
        npm install
      env:
        CI: true
    - name: Build
      run: npm build:pre
      if: startsWith(github.ref, 'refs/tags/')
    - name: Release
      uses: softprops/action-gh-release@v1
      if: startsWith(github.ref, 'refs/tags/')
      with:
        files: preCompiled.zip
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}      
