name: Create precomputed archive

on: push

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: Installing Node
      uses: actions/setup-node@v1
      with:
        node-version: 10.x
    - name: Installing dependencies
      run: |
        npm install --global yarn
        yarn
      env:
        CI: true
    - name: Build
      run: ls && yarn build:pre
    - name: Release
      uses: softprops/action-gh-release@v1
      with:
        files: preCompiled.zip
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}      
